### ISSUE TITLE
PlayFabHttp Error

### ISSUE THREAD

**Issue by jrDev1** [PlayFab/UnitySDK#150]
Throws this error:

Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs(117,61): error CS0103: The name `_devKey' does not exist in the current context

which is this line:
_devKey = PlayFabSettings.DeveloperSecretKey ?? _devKey;

So it seems that this variable wasn't declared.

Thanks,
jrDev

**Comment by MarcoWilliamsPF** [comment]
Fix is being submitted.. 
Fix is: 

#if ENABLE_PLAYFABADMIN_API || ENABLE_PLAYFABSERVER_API
            _internalHttp.DevKey = PlayFabSettings.DeveloperSecretKey ?? _internalHttp.DevKey;
#endif

**Comment by rainerlonau** [comment]
I've got another error at that line:
`NullReferenceException: Object reference not set to an instance of an object
PlayFab.Internal.PlayFabHttp.Awake () (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:117)`
"_internalHttp" seems to be null at that time. When debugging it goes from line 75 (CreateInstance(); // Invoke the SingletonMonoBehaviour) to the Awake function. But "_internalHttp" is created in line 79/82?!

**Comment by rainerlonau** [comment]
I commented out the following line now and I can login successfully. But I'm not aware of what the line does. Please advise if this is fine or how I should fix the problem correctly. 
`//            CreateInstance(); // Invoke the SingletonMonoBehaviour`
Thanks

**Comment by rainerlonau** [comment]
I read some more comments and saw that I followed the guide "To make server API calls" in the readme. Since I guess this isn't really important to me yet, I removed the ENABLE_PLAYFABSERVER_API custom define. I uncomment the CreateInstance(); line and this works now without an error. So that's fine for me at the moment, but I guess you should have a look for people using the custom define.
Cheers

**Comment by pgilmorepf** [comment]
The fix for the initial issue in this thread has been posted:
https://api.playfab.com/releaseNotes/#160721

We've noticed the CreateInstance/Awake error but it has not yet been resolved.
We need more details about how you guys are getting that error.
See the most recent posting of this issue, and my request to get this conversation moved to the forum.
https://github.com/PlayFab/UnitySDK/issues/156
