### ISSUE TITLE
Only one ScheduleNotification

### ISSUE THREAD

**Issue by pmanzano** [PlayFab/UnitySDK#194]
In android, when you are trying to send more than one SheduleNotification, only one is sent, with the content and date of the last one. I think it's because in the `PlayFabNotificationSender.java` -> `ScheduleNotification` the Id of the PendingIntent is hardcoded to `0`. 
After changing that hardcoded `0` to use the notifyPackage.Id (in my case it is an int), I'm able to send several local notifications.

Also, this is an issue when canceling the local notifications, as the Id won't match the notification sended (the getNotificationId always ads 1 to the previous request of getNotificationId).

**Comment by pgilmorepf** [comment]
Thanks for catching this!

I'm testing out a change for PlayFabNotificationPackage.Id to always be the java hashCode() for the message string.
This will mean that two separate but identical push notifications will share the same Id, which isn't perfect.
But it should be sufficiently unique so that any two unique messages will have unique Id's, and will show up as two separate messages. I've also changed the Id to an int to match the datatype in the PendingIntent.getBroadcast parameter you pointed out, as well as removed the part that assigns it a UUID, which won't fit in an int.

Theoretically, two different strings can have the same hash, but In practice, I've been using this technique for years, and I've never seen it actually happen.  But of course there's a 1/2Bn chance for two messages to overlap, unless deliberately crafted to do so.

That's my current plan, and it's in testing now.
If it works, then this fix is en-route.
It'll probably be live in the next SDK release (v2.22, or possibly 2.23)

**Comment by pgilmorepf** [comment]
It looks like everything worked and all my updates do all the right things.  You can schedule multiple notifications, cancel notifications, and all that jazz.
The fix will definitely be in the next release, UnitySdk 2.22
Thanks for reporting this!
