### ISSUE TITLE
The issue still not fixed for Android. 

### ISSUE THREAD

**Issue by ttesla** [PlayFab/UnitySDK#216]
See the issue here: https://community.playfab.com/answers/33222/view.html

Solution:
```
var serializer   = PluginManager.GetPlugin<ISerializerPlugin>(PluginContract.PlayFab_Serializer);
var httpResult = PlayFabSimpleJson.DeserializeObject<HttpResponseObject>(response);
```

**Comment by pgilmorepf** [comment]
I'm going to bubble up some comments from the thread that are likely important/relevant:

_tesla: Ok. Found the problem for myself. This was happening because of the IL2Cpp stripping setting. Under the Optimization part, I Changed "Managed Stripping Level" = "Low" . It was "Medium" before._

Your suggested code would actually break our strategy for allowing the replacement of the Json serializer (anybody who replaces it would suddenly stop working).
We will investigate, and see if we can reproduce and fix the issue.

**Comment by ttesla** [comment]
Sorry to report back to here. This issue should be closed. 

The setting _PlayerSettings -> Managed Stripping Level = "Low"_  fixes the problem. 
The default is already "Low" but somehow if you set it a higher level to get a better stripped build, you end up with a broken build. I guess it stripes out some necessary parts of playfab.
