### ISSUE TITLE
Remove Application.runInBackground = true

### ISSUE THREAD

**Issue by kamyker** [PlayFab/UnitySDK#223]
1. On android and ios this option doesn't do anthing. It's forced false. https://docs.unity3d.com/ScriptReference/Application-runInBackground.html
2. UnityWebRequest is not that stupid, it doesn't run on main thread. Even if application is paused on PC/Linux it still correctly completes.

**Comment by pgilmorepf** [comment]
Hello kamyker, thanks for reporting your concern.
Our code runs on all platforms, Win, Mac, Linux, Xbox, PS4, Switch, and of course iOS, and Android.
We also have an optional alternate HTTP layer, which bypasses UnityWebRequest, and our custom HTTP layer requires this.

We're going to mark this issue as "by design" because as you say: in the worst case, it's simply not necessary. But in many cases, it is required. And it introduces unnecessary complexity to set it conditionally.

**Comment by kamyker** [comment]
#224
