### ISSUE TITLE
Playfab Admin Models do not include West Us

### ISSUE THREAD

**Issue by MScottAdams** [PlayFab/UnitySDK#229]
originally reported: https://github.com/PlayFab/gsdk/issues/50 

The PlayFabAdminModels.cs  region enum does not include the West US just EuWest.

    public enum Region
    {
        USCentral,
        USEast,
        EUWest,
        Singapore,
        Japan,
        Brazil,
        Australia
    }

**Comment by pgilmorepf** [comment]
1. This SDK is not related to the GSDK. They are operated by independent teams. The source bug: https://github.com/PlayFab/gsdk/issues/50 is absolutely relevant, and should stay there. This bug is not, and should not be linked.
2. This SDK is auto-generated to support the regions available by the SDK each time it is published. It will be automatically updated to match the regions that are available for those API methods at each publish.
3. There does appear to be a discrepancy between AzureRegion and Region, which seem to be parallel enums, with different contents. This is part of the auto-generation from the pf-main server though, and should be filed elsewhere. https://github.com/PlayFab/UnitySDK/blob/7d2b13284271404527d2dd0b93202d9802b3e30e/ExampleTestProject/Assets/PlayFabSDK/Matchmaker/PlayFabMatchmakerModels.cs#L147

I do accept that the AzureRegion and Region enums with different contents is confusing and problematic, so I'll file the bug internally on the server team.

**Comment by pgilmorepf** [comment]
OH let's see... it's been removed from the GSDK.
At any rate, all my other comments stand.
I'm going to leave this issue closed, as it's a service issue, not an SDK one.
And repeat that I've forwarded the issue to the appropriate team internally.
