### ISSUE TITLE
Android Build Failed: AndroidManifest.xml:52: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

### ISSUE THREAD

**Issue by Irin1178** [PlayFab/UnitySDK#48]
Started getting this on Android builds only

**Comment by MarcoWilliamsPF** [comment]
@Irin1178   if you look at   /Assets/Plugins/Android/Res/Values/version.xml   the key "googl_play_services_version"  should be in there.  

Can you check to see if that is in your project?

see:  https://github.com/PlayFab/UnitySDK/blob/master/PlayFabClientSample/Assets/Plugins/Android/res/values/version.xml

**Comment by Irin1178** [comment]
I do have this file.

**Comment by Irin1178** [comment]
For what its worth, I've tried completely removing playfab from the project and re-extracting the latest unitypackage file and am still receiving this. I've also made sure my android SDK contains the google play services should it need to reference it

**Comment by Irin1178** [comment]
To work around build failure for the time being, I've commented out the lines in AndroidManifest.xml

!-- End GCM 
      <meta-data
          android:name="com.google.android.gms.version"
          android:value="@integer/google_play_services_version" />
         Android GCM Plugin -->

As our game is not making use of google play services in its current states.

**Comment by JohnTube** [comment]
"First of all, if you are building a plugin as a library, the recommended way is to copy the entire project folder into Plugins/Android/your_library_name/ (including built jar in bin/) - this ensures you get the manifest and resources merged correctly.
" [source](http://forum.unity3d.com/threads/android-non-main-activity-plugin-not-working-class-not-found-exception.287818/#post-1914018)

So putting the whole Play Services project provided by Google instead of just the .jar file could solve this. But this could create conflicts with other assets.

**Comment by zac-playfab** [comment]
@Irin1178 
Hey Irin, 
I just wanted to check in to see if you got this resolved. I will be closing this out this week unless you are looking for additional support.
